### ISSUE TITLE
Pre-upgrade: postgresql case sensitive hostname comparison

### ISSUE THREAD

**Issue by Carus11** [sassoftware/viya-ark#40]
In the pre upgrade playbook file:
https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-upgrade/pre_upgrade/verify-postgres-server.yml

line 201, 209:
```
        - name: Compare the secondary node_type between the PostgreSQL check output and vars.yml
          assert:
            that: ansible_fqdn in obtain_postgres_secondary_hostname.stdout
[....]
    - name: Compare the host names from the PostgreSQL check with the host names in the inventory file
      assert:
        that: ansible_fqdn in obtain_postgres_hostname.stdout
```
The assert will fail if the case does not match. 
I am wondering if this is a valid requirement as domain names are supposed to be case insensitive?

**Comment by koicarer** [comment]
The value of the variable NODE_TYPE defined in vars.yml must be either P or S.

**Comment by Carus11** [comment]
@koicarer I dont see how that is related to my question. I am asking about hostname comparisons: case sensitive or should it be case insensitive?

**Comment by koicarer** [comment]
The hostname defined in the inventory.ini must be found in the output "postgres_status.out" so I think it is case sensitive.

**Comment by AlissaSchleich** [comment]
This has been resolved/answered

**Comment by Carus11** [comment]
This isnt really resolved. This breaks the pre-upgrade playbook when one has a mixed case hostname in inventory.ini, for example: SASViya1.example.com
The assert fails because it is doing a case sensitive comparison against output that is forced to all lowercase. I worked around this issue by casting both values to lowercase. I would have preferred the server setup be all lowercase hostnames but the system administrators argue that it shouldnt matter because hostnames are by definition supposed to be case-insensitive (RFC 4343)

**Comment by koicarer** [comment]
Thanks for the clarification. We are currently validating the behavior of
the postgres utility to see if they force it's output to be all in lower
case.
If they do, we will update the playbook accordingly.

FYI, the playbook automates the step stated in the following link.
https://go.documentation.sas.com/?cdcId=calcdc&cdcVersion=3.4&docsetId=dplyml0phy0lax&docsetTarget=p1gjykqt2n4ichn1vv2ev6i8gh50.htm&locale=en
